spring: 
  profiles:
    active:
    - dev
---
server: 
  port: 8210
spring: 
  profiles: dev
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 8220
spring: 
  profiles: test
  application: 
    name: microservice-config-client
eureka: 
  client: 
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/